### ISSUE TITLE
How to setup gunicorn with this example

### ISSUE THREAD

**Issue by dhanababum** [bdarnell/django-tornado-demo#8]
Hi bdarnell,
     It is very usefull repo for me. I am runing tornado server and it is working fine, But when I am using gunicorn i'm facing some issues. Can you please look at this error,

Traceback (most recent call last):
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    **import**(module)
  File "/home/dhana/webrtc/neonarc2/tornado_server.py", line 10, in <module>
    from rtc import render_view
  File "/home/dhana/webrtc/neonarc2/rtc/**init**.py", line 7, in <module>
    django.setup()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/dhana/webrtc/neonarc2/user_management/models.py", line 3, in <module>
    from allauth.account.models import EmailAddress
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/allauth/account/models.py", line 20, in <module>
    from .managers import EmailAddressManager, EmailConfirmationManager
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/allauth/account/managers.py", line 57, in <module>
    class EmailConfirmationManager(models.Manager):
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/utils/deprecation.py", line 58, in **new**
    wrapper = warn_about_renamed_method(class_name, *renamed_method)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/gtornado.py", line 36, in handle_exit
    self.stop()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/gtornado.py", line 117, in stop
    PeriodicCallback(self.stop_ioloop, 1000, io_loop=self.ioloop).start()
AttributeError: 'TornadoWorker' object has no attribute 'ioloop'
Traceback (most recent call last):
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
    worker.init_process()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    **import**(module)
  File "/home/dhana/webrtc/neonarc2/tornado_server.py", line 10, in <module>
    from rtc import render_view
  File "/home/dhana/webrtc/neonarc2/rtc/**init**.py", line 7, in <module>
    django.setup()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/dhana/webrtc/neonarc2/user_management/models.py", line 3, in <module>
    from allauth.account.models import EmailAddress
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/allauth/account/models.py", line 20, in <module>
    from .managers import EmailAddressManager, EmailConfirmationManager
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/allauth/account/managers.py", line 57, in <module>
    class EmailConfirmationManager(models.Manager):
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/django/utils/deprecation.py", line 58, in **new**
    wrapper = warn_about_renamed_method(class_name, *renamed_method)
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/gtornado.py", line 36, in handle_exit
    self.stop()
  File "/home/dhana/webrtc/env/local/lib/python2.7/site-packages/gunicorn/workers/gtornado.py", line 117, in stop
    PeriodicCallback(self.stop_ioloop, 1000, io_loop=self.ioloop).start()
AttributeError: 'TornadoWorker' object has no attribute 'ioloop'
[2015-03-15 11:41:34 +0000] [9697] [INFO] Worker exiting (pid: 9697)

**Comment by bdarnell** [comment]
This repo is designed to be run with Tornado's built-in HTTPServer, not gunicorn. I believe it will need to be modified to work with gunicorn but I have never used gunicorn so I can't tell you what changes are needed.
